default['rails-lastmile']['app_dir'] = "/vagrant"
default['rails-lastmile']['ruby_version'] = "1.9.3-p392"
default['rails-lastmile']['postgresql']['username'] = "nilesh"
default['rails-lastmile']['postgresql']['password'] = "test"
default['rails-lastmile']['postgresql']['dbname'] = "mannupig_development"
